### PR TITLE
[ENHANCEMENT] Autoinstall scripts for Arch and Pop_OS!

### PR DESCRIPTION
**Pull request by JulianGR**
As requested, here are the autoinstall scripts. I have thoroughly tested the Pop_OS! script but not the arch one because I don't pilot as much. I guess it works (I've just added the commads from all the steps of the installation).

Cheers =)

### CODE REVIEW

**Comment by Crylia** [comment]
I'll setup two VM's to test those scripts, if someone using arch wants to test it please do so I don't have to setup arch again :sob: .
Once I tested it I'll merge it or notify you if something is wrong.

**Comment by Crylia** [comment]
You need to add "libxcb-xfixes0-dev" to the installation since won't compile awesomewm otherwise.

**Comment by Crylia** [comment]
"libev-dev"
"libxcb-damage0-dev"
"libxcb-sync-dev"
"libxcb-composite0-dev"
"libxcb-present-dev"
"uthash-dev"
"libconfig-dev"
"libgl-dev"
Those are all missing to compile rofi.

**Comment by Crylia** [comment]
The MesloLGS fonts aren't installed correctly and it would be nice if alacritty was installed too so you got a terminal to start.
Currently the fonts downloaded with wget land in $HOME but should be in $HOME/.fonts

**Comment by Crylia** [comment]
Some more dependencies are missing for rofi I think:
"libxcb-emwh-dev"

you also need to use 
`ninja -C build`
before doing 
`ninja -C build install`
Otherwise you will get an error

**Comment by JulianGR** [comment]
Okay you can check it now, I've made all the changes you've said =)

**Comment by Crylia** [comment]
I misstyped the package `libxcb-emwh-dev` but it should be `libxcb-ewmh-dev`.

It also seems that rofi needs more dependencies
- bison
- flex
- check

I also had a weird problem where ninja and meson were installed, but I had to reinstall them for rofi to work? Maybe install it in its own line idk.
Also rofi doesn't need sudo as I thought earlier, so Its just

- ninja -C build
- ninja -C build install

I hope I got it right now.

**Comment by Crylia** [comment]
Alright this seems to work flawless now at least for the pop_os script. (tested in a fresh install of 22.04)
Sadly I cannot really test the Archlinux script for now so I will simply assume that Its fine from taking a closer look to it.

Thanks very much for your contribution :)

**Comment by JulianGR** [comment]
Thank you for accepting my pull request =)

**Pull request merged**
